#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[0;31m'

# Get commit message:
# Ref: https://stackoverflow.com/a/44423052
INPUT_FILE=$1
COMMIT_MESSAGE=`head -n1 $INPUT_FILE`
echo $COMMIT_MESSAGE
PATTERN="(feat|fix|style)(: )(.)+"

if ! [[ "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
  echo "${RED}❌ Bad commit message, please change and try again!"
  exit 1
fi
